### ISSUE TITLE
Issue with config

### ISSUE THREAD

**Issue by Gunaranjan66** [james-stevens/pyrar#37]
not able to run with docker because of the policy.json file is not found in config folder. Pls can you share how to create the policy.json file or can you make a default config file add in dockerfile

`Traceback (most recent call last):
  File "/opt/pyrar/python/bin/policy_subst.py", line 9, in <module>
    from librar.policy import this_policy as policy
  File "/opt/pyrar/python/librar/policy.py", line 84, in <module>
    this_policy = Policy()
  File "/opt/pyrar/python/librar/policy.py", line 63, in __init__
    self.file = fileloader.FileLoader(static.POLICY_FILE)
  File "/opt/pyrar/python/librar/fileloader.py", line 49, in __init__
    self.check_for_new()
  File "/opt/pyrar/python/librar/fileloader.py", line 52, in check_for_new
    if (new_time := have_newer(self.last_mtime, self.filename)) is None:
  File "/opt/pyrar/python/librar/fileloader.py", line 31, in have_newer
    raise PermissionError(f"'{file_name}' not found or not readable")
PermissionError: '/opt/pyrar/config/policy.json' not found or not readable`

**Comment by james-stevens** [comment]
there's a full install guide in `INSTALL_ON_UBUNTU_SERVER` now
